name: Publish Report to Wiki

on:
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Clone Wiki repository (with token)
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Create Security Scan Report
        run: |
          mkdir -p wiki/reports
          echo "## Security Scan Report - ${{ github.run_id }}" > wiki/reports/security-scan.md
          echo "- Repository: ${{ github.repository }}" >> wiki/reports/security-scan.md
          echo "- Workflow: ${{ github.workflow }}" >> wiki/reports/security-scan.md
          echo "- Status: ✅ Success" >> wiki/reports/security-scan.md
          echo "- Triggered by: ${{ github.actor }}" >> wiki/reports/security-scan.md
          echo "- Date: $(date)" >> wiki/reports/security-scan.md

      - name: Commit and Push Report
        run: |
          cd wiki
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update: Security scan report for run ${{ github.run_id }}"
          git push origin master
