name: Publish to GitHub Wiki

on:
  workflow_dispatch:  # Manually trigger or add 'push'/'pull_request' triggers

jobs:
  publish-to-wiki:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Clone Wiki repository
        run: |
          git clone https://x-access-token:${{ secrets.WIKI_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki


      - name: Prepare Wiki Content
        run: |
          mkdir -p wiki/reports
          echo "## Security Scan Report - ${{ github.run_id }}" > wiki/reports/security-scan.md
          echo "- Repository: ${{ github.repository }}" >> wiki/reports/security-scan.md
          echo "- Workflow: ${{ github.workflow }}" >> wiki/reports/security-scan.md
          echo "- Status: ✅ Success" >> wiki/reports/security-scan.md
          echo "- Triggered by: ${{ github.actor }}" >> wiki/reports/security-scan.md
          echo "- Date: $(date)" >> wiki/reports/security-scan.md

      - name: Commit and Push to Wiki
        run: |
          cd wiki
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Updated report for run ${{ github.run_id }}"

      - name: Push to Wiki
        run: |
          cd wiki
          git push origin master

