name: Notify Slack on Push

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚀 New push to *${{ github.repository }}* on branch *${{ github.ref_name }}* by *${{ github.actor }}*"
