name: Slack Notification

on:
  workflow_dispatch:  # You can also use push or other triggers

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: dev  # 👈 IMPORTANT: Specify the environment name here
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK }}
          SLACK_MESSAGE: "✅ GitHub Action ran in *${{ github.repository }}* by *${{ github.actor }}*"
